use chrono::{DateTime, Duration, Local, Utc};
use image::{imageops::FilterType, DynamicImage};
use rusqlite::{params, Connection};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::{collections::HashMap, fs, io::{BufReader, Read}, path::{Path, PathBuf}};
use tauri::Manager;
use uuid::Uuid;
use walkdir::WalkDir;

const CATEGORIES: [&str; 8] = ["document", "image", "video", "audio", "installer", "archive", "other", "to_archive"];

#[derive(Debug, Clone, Serialize, Deserialize)] struct Source { path: String, recursive: bool, destinations: HashMap<String, String> }
#[derive(Debug, Clone, Serialize, Deserialize)] struct Config { sources: Vec<Source>, pinned: Vec<String> }
#[derive(Debug, Clone, Serialize, Deserialize)] struct DeskFile { id: String, path: String, name: String, extension: String, size: u64, modified_at: String, category: String, status: String, duplicate_group: Option<String>, similar_group: Option<String>, suggested_destination: String }
#[derive(Debug, Clone, Serialize, Deserialize)] struct Scan { scanned_at: String, files: Vec<DeskFile>, duplicate_groups: HashMap<String, Vec<String>>, similar_groups: HashMap<String, Vec<String>>, errors: Vec<String> }
#[derive(Debug, Clone, Serialize, Deserialize)] struct PlanItem { source: String, destination: String, conflict: bool, reason: String }
#[derive(Debug, Clone, Serialize, Deserialize)] struct HistoryRow { id: i64, moved_at: String, entries: Vec<PlanItem>, undone: bool }
#[derive(Debug, Clone, Serialize, Deserialize)] struct DailyReport { date: String, total_files: usize, needs_sorting: usize, archivable: usize, duplicate_groups: usize, similar_groups: usize, recent_operations: usize }

fn data_path() -> Result<PathBuf, String> { let path = dirs::data_local_dir().ok_or("找不到本地应用数据目录")?.join("CleanDesk"); fs::create_dir_all(&path).map_err(|e| e.to_string())?; Ok(path.join("cleandesk.db")) }
fn db() -> Result<Connection, String> { let conn = Connection::open(data_path()?).map_err(|e| e.to_string())?; conn.execute_batch("CREATE TABLE IF NOT EXISTS kv (key TEXT PRIMARY KEY, value TEXT NOT NULL); CREATE TABLE IF NOT EXISTS history (id INTEGER PRIMARY KEY AUTOINCREMENT, moved_at TEXT NOT NULL, entries TEXT NOT NULL, undone INTEGER NOT NULL DEFAULT 0);").map_err(|e| e.to_string())?; Ok(conn) }
fn desktop() -> String { dirs::desktop_dir().unwrap_or_else(|| dirs::home_dir().unwrap_or_else(|| PathBuf::from("."))).to_string_lossy().to_string() }
fn default_config() -> Config { Config { sources: vec![Source { path: desktop(), recursive: false, destinations: HashMap::new() }], pinned: vec![] } }
fn load_config() -> Result<Config, String> { let conn = db()?; let value: Option<String> = conn.query_row("SELECT value FROM kv WHERE key='config'", [], |r| r.get(0)).ok(); Ok(value.and_then(|v| serde_json::from_str(&v).ok()).unwrap_or_else(default_config)) }
fn set_kv(key: &str, value: &str) -> Result<(), String> { db()?.execute("INSERT INTO kv(key,value) VALUES(?1,?2) ON CONFLICT(key) DO UPDATE SET value=excluded.value", params![key, value]).map_err(|e| e.to_string())?; Ok(()) }
fn get_last_scan_inner() -> Result<Option<Scan>, String> { let conn = db()?; let value: Option<String> = conn.query_row("SELECT value FROM kv WHERE key='last_scan'", [], |r| r.get(0)).ok(); Ok(value.and_then(|v| serde_json::from_str(&v).ok())) }

fn category(ext: &str) -> &'static str { match ext.to_lowercase().as_str() { "doc"|"docx"|"pdf"|"txt"|"rtf"|"xls"|"xlsx"|"ppt"|"pptx"|"md" => "document", "jpg"|"jpeg"|"png"|"gif"|"webp"|"bmp"|"heic" => "image", "mp4"|"mkv"|"mov"|"avi"|"webm" => "video", "mp3"|"wav"|"flac"|"m4a"|"aac" => "audio", "exe"|"msi"|"msix"|"appx" => "installer", "zip"|"rar"|"7z"|"tar"|"gz" => "archive", _ => "other" } }
fn hidden(path: &Path) -> bool { path.file_name().and_then(|n| n.to_str()).map(|n| n.starts_with('.')).unwrap_or(false) }
fn suggested(source: &Source, kind: &str) -> String { source.destinations.get(kind).cloned().unwrap_or_else(|| Path::new(&source.path).join(match kind { "document"=>"文档", "image"=>"图片", "video"=>"视频", "audio"=>"音频", "installer"=>"安装包", "archive"=>"压缩包", _=>"其他" }).to_string_lossy().to_string()) }
fn sha256(path: &Path) -> Result<String, String> { let file = fs::File::open(path).map_err(|e| e.to_string())?; let mut reader = BufReader::new(file); let mut hash = Sha256::new(); let mut buf = [0; 65536]; loop { let n = reader.read(&mut buf).map_err(|e| e.to_string())?; if n == 0 { break; } hash.update(&buf[..n]); } Ok(format!("{:x}", hash.finalize())) }
fn doc_text(path: &Path) -> Option<String> { match path.extension()?.to_str()?.to_ascii_lowercase().as_str() { "pdf" => pdf_extract::extract_text(path).ok(), "docx" => { let file = fs::File::open(path).ok()?; let mut zip = zip::ZipArchive::new(file).ok()?; let mut xml = String::new(); zip.by_name("word/document.xml").ok()?.read_to_string(&mut xml).ok()?; Some(xml.replace("</w:t>", " ").replace(|c: char| c == '<' || c == '>', " ").split_whitespace().collect::<Vec<_>>().join(" ")) }, _ => None } }
fn image_hash(path: &Path) -> Option<String> { let img = image::open(path).ok()?; let grey = DynamicImage::ImageLuma8(img.resize_exact(8, 8, FilterType::Triangle).to_luma8()); let data = grey.to_luma8().into_raw(); let avg = data.iter().map(|v| *v as u32).sum::<u32>() / 64; Some(data.iter().map(|v| if *v as u32 >= avg { '1' } else { '0' }).collect()) }
fn token_similarity(a: &str, b: &str) -> f32 { let aa: std::collections::HashSet<_> = a.split_whitespace().filter(|x| x.len() > 1).take(5000).collect(); let bb: std::collections::HashSet<_> = b.split_whitespace().filter(|x| x.len() > 1).take(5000).collect(); if aa.is_empty() || bb.is_empty() { return 0.0; } aa.intersection(&bb).count() as f32 / aa.union(&bb).count() as f32 }
fn hamming(a: &str, b: &str) -> usize { a.bytes().zip(b.bytes()).filter(|(x,y)| x != y).count() }
fn unique_target(target: PathBuf) -> PathBuf { if !target.exists() { return target; } let stem = target.file_stem().and_then(|x| x.to_str()).unwrap_or("file"); let ext = target.extension().and_then(|x| x.to_str()).map(|e| format!(".{e}")).unwrap_or_default(); for n in 2..10000 { let probe = target.with_file_name(format!("{stem} ({n}){ext}")); if !probe.exists() { return probe; } } target.with_file_name(format!("{stem}-{}{}", Uuid::new_v4(), ext)) }

#[tauri::command] fn get_config() -> Result<Config, String> { load_config() }
#[tauri::command] fn save_config(config: Config) -> Result<(), String> { set_kv("config", &serde_json::to_string(&config).map_err(|e| e.to_string())?) }
#[tauri::command] fn get_last_scan() -> Result<Option<Scan>, String> { get_last_scan_inner() }

#[tauri::command]
fn scan_files() -> Result<Scan, String> {
 let config = load_config()?; let now = Utc::now(); let mut files = Vec::new(); let mut errors = Vec::new(); let mut source_for_path: HashMap<String, Source> = HashMap::new();
 for source in &config.sources { let root = PathBuf::from(&source.path); if !root.exists() { errors.push(format!("目录不存在：{}", source.path)); continue; } let walker = if source.recursive { WalkDir::new(&root) } else { WalkDir::new(&root).max_depth(1) }; for entry in walker.into_iter().filter_map(Result::ok) { let path = entry.path(); if path == root || !entry.file_type().is_file() || hidden(path) { continue; } let meta = match path.metadata() { Ok(v)=>v, Err(e)=>{ errors.push(format!("无法读取 {}：{e}", path.display())); continue; } }; let modified: DateTime<Utc> = meta.modified().map(DateTime::<Utc>::from).unwrap_or(now); let age = now.signed_duration_since(modified); let ext = path.extension().and_then(|s| s.to_str()).unwrap_or("").to_string(); let kind = category(&ext).to_string(); let path_string = path.to_string_lossy().to_string(); let status = if config.pinned.contains(&path_string) || age < Duration::days(7) { "keep" } else if age > Duration::days(30) { "archivable" } else { "needs_sorting" }.to_string(); source_for_path.insert(path_string.clone(), source.clone()); files.push(DeskFile { id: Uuid::new_v4().to_string(), path: path_string, name: path.file_name().and_then(|s| s.to_str()).unwrap_or("未命名").to_string(), extension: ext, size: meta.len(), modified_at: modified.to_rfc3339(), category: kind.clone(), status, duplicate_group: None, similar_group: None, suggested_destination: suggested(source, &kind) }); } }
 let mut sizes: HashMap<u64, Vec<usize>> = HashMap::new(); for (i,f) in files.iter().enumerate() { sizes.entry(f.size).or_default().push(i); } let mut duplicate_groups = HashMap::new(); for ids in sizes.values().filter(|x| x.len() > 1) { let mut hashes: HashMap<String, Vec<usize>> = HashMap::new(); for &i in ids { if let Ok(hash) = sha256(Path::new(&files[i].path)) { hashes.entry(hash).or_default().push(i); } } for members in hashes.values().filter(|x| x.len() > 1) { let id = format!("dup-{}", Uuid::new_v4()); let paths = members.iter().map(|&i| files[i].path.clone()).collect(); for &i in members { files[i].duplicate_group = Some(id.clone()); files[i].status = "duplicate".into(); } duplicate_groups.insert(id, paths); } }
 let eligible: Vec<usize> = files.iter().enumerate().filter_map(|(i,f)| if f.duplicate_group.is_none() && (f.category == "document" || f.category == "image") { Some(i) } else { None }).collect(); let mut similar_groups = HashMap::new(); for a in 0..eligible.len() { for b in (a+1)..eligible.len() { let i=eligible[a]; let j=eligible[b]; let match_found = if files[i].category == "document" && files[j].category == "document" { match (doc_text(Path::new(&files[i].path)), doc_text(Path::new(&files[j].path))) { (Some(x),Some(y)) => token_similarity(&x,&y) >= 0.80, _ => false } } else if files[i].category == "image" && files[j].category == "image" { match (image_hash(Path::new(&files[i].path)), image_hash(Path::new(&files[j].path))) { (Some(x),Some(y)) => hamming(&x,&y) <= 8, _ => false } } else { false }; if match_found { let id = files[i].similar_group.clone().unwrap_or_else(|| format!("sim-{}", Uuid::new_v4())); for &index in &[i,j] { files[index].similar_group=Some(id.clone()); files[index].status="similar".into(); } let paths = files.iter().filter(|f| f.similar_group.as_deref()==Some(&id)).map(|f| f.path.clone()).collect(); similar_groups.insert(id, paths); } } }
 let scan = Scan { scanned_at: Utc::now().to_rfc3339(), files, duplicate_groups, similar_groups, errors }; set_kv("last_scan", &serde_json::to_string(&scan).map_err(|e|e.to_string())?)?; Ok(scan)
}

#[tauri::command]
fn build_plan(paths: Vec<String>) -> Result<Vec<PlanItem>, String> { let scan = get_last_scan_inner()?.ok_or("请先扫描目录")?; let chosen: Vec<_> = scan.files.into_iter().filter(|f| paths.contains(&f.path) && f.status != "duplicate" && f.status != "similar" && f.status != "keep").collect(); Ok(chosen.into_iter().map(|f| { let target = unique_target(PathBuf::from(f.suggested_destination).join(&f.name)); PlanItem { source:f.path, conflict: target.file_name().and_then(|n|n.to_str()).map(|n|n != f.name).unwrap_or(false), destination:target.to_string_lossy().to_string(), reason: if f.status=="archivable" { "超过 30 天未修改".into() } else { "按文件类型分类".into() } }}).collect()) }
#[tauri::command]
fn execute_plan(items: Vec<PlanItem>) -> Result<(), String> { if items.is_empty() { return Ok(()); } let mut done: Vec<PlanItem> = vec![]; for item in items { let source=Path::new(&item.source); let destination=unique_target(PathBuf::from(&item.destination)); if !source.exists() { continue; } fs::create_dir_all(destination.parent().ok_or("无效目标目录")?).map_err(|e|e.to_string())?; fs::rename(source, &destination).map_err(|e| format!("无法移动 {}：{e}", source.display()))?; done.push(PlanItem { destination: destination.to_string_lossy().to_string(), ..item }); } let entries=serde_json::to_string(&done).map_err(|e|e.to_string())?; db()?.execute("INSERT INTO history(moved_at,entries,undone) VALUES(?1,?2,0)", params![Utc::now().to_rfc3339(), entries]).map_err(|e|e.to_string())?; Ok(()) }
#[tauri::command]
fn get_history() -> Result<Vec<HistoryRow>, String> { let conn=db()?; let mut stmt=conn.prepare("SELECT id,moved_at,entries,undone FROM history ORDER BY id DESC").map_err(|e|e.to_string())?; let rows=stmt.query_map([], |r| { let entries:String=r.get(2)?; let list:Vec<PlanItem>=serde_json::from_str(&entries).unwrap_or_default(); Ok(HistoryRow{id:r.get(0)?,moved_at:r.get(1)?,entries:list,undone:r.get::<_,i64>(3)? != 0}) }).map_err(|e|e.to_string())?; rows.collect::<Result<Vec<_>,_>>().map_err(|e|e.to_string()) }
#[tauri::command]
fn undo_operation(id: i64) -> Result<(), String> { let conn=db()?; let (entries,undone):(String,i64)=conn.query_row("SELECT entries,undone FROM history WHERE id=?1",params![id],|r|Ok((r.get(0)?,r.get(1)?))).map_err(|_|"未找到整理记录".to_string())?; if undone != 0 { return Err("该操作已经撤销".into()); } let items:Vec<PlanItem>=serde_json::from_str(&entries).map_err(|e|e.to_string())?; for item in items { let current=Path::new(&item.destination); if current.exists() { let original=unique_target(PathBuf::from(&item.source)); if let Some(parent)=original.parent(){fs::create_dir_all(parent).map_err(|e|e.to_string())?;} fs::rename(current,original).map_err(|e|e.to_string())?; } } conn.execute("UPDATE history SET undone=1 WHERE id=?1",params![id]).map_err(|e|e.to_string())?; Ok(()) }
#[tauri::command]
fn get_daily_report() -> Result<DailyReport, String> { let scan=get_last_scan_inner()?; let files=scan.as_ref().map(|s|&s.files).cloned().unwrap_or_default(); let history=get_history()?; Ok(DailyReport { date: Local::now().format("%Y-%m-%d").to_string(), total_files:files.len(), needs_sorting:files.iter().filter(|f|f.status=="needs_sorting").count(), archivable:files.iter().filter(|f|f.status=="archivable").count(), duplicate_groups:scan.as_ref().map(|s|s.duplicate_groups.len()).unwrap_or(0), similar_groups:scan.as_ref().map(|s|s.similar_groups.len()).unwrap_or(0), recent_operations:history.iter().filter(|h|!h.undone).count() }) }

pub fn run() { tauri::Builder::default().plugin(tauri_plugin_dialog::init()).plugin(tauri_plugin_opener::init()).setup(|app| { let _ = app.handle(); Ok(()) }).invoke_handler(tauri::generate_handler![get_config, save_config, get_last_scan, scan_files, build_plan, execute_plan, get_history, undo_operation, get_daily_report]).run(tauri::generate_context!()).expect("error while running CleanDesk"); }

#[cfg(test)] mod tests { use super::*; #[test] fn categorises_extensions() { assert_eq!(category("PDF"), "document"); assert_eq!(category("jpg"), "image"); assert_eq!(category("msi"), "installer"); } #[test] fn compares_text_similarity() { assert!(token_similarity("alpha beta gamma delta", "alpha beta gamma delta extra") > .8); assert!(token_similarity("one two", "blue green") < .2); } #[test] fn compares_image_hashes() { assert!(hamming("1010", "1011") <= 1); assert!(hamming("1010", "0101") >= 3); } }
